services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: /app  # Dockerfile dagi WORKDIR bilan bir xil bo'lishi kerak
    volumes:
      - .:/app         # Fayllarni /app papkasiga ulaymiz
    command: python main.py
    restart: always
    env_file:
      - ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"